/**
 * Created by sabir on 18.12.16.
 */

//users
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const LOAD_USERS = 'LOAD_USERS'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const INITIALIZE_AUTH = 'INITIALIZE_AUTH'
export const INITIALIZE_AUTH_SUCCESS = 'INITIALIZE_AUTH_SUCCESS'
export const INITIALIZE_AUTH_FAIL = 'INITIALIZE_AUTH_FAIL'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'



//organization
export const LOAD_ORGANIZATION = 'LOAD_ORGANIZATION'
export const LOAD_ORGANIZATION_SUCCESS = 'LOAD_ORGANIZATION_SUCCESS'
export const LOAD_ORGANIZATION_FAIL = 'LOAD_ORGANIZATION_FAIL'


//groups
export const CREATE_GROUP = 'CREATE_GROUP'
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL'

export const DELETE_GROUP = 'DELETE_GROUP'
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL'

export const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP'
export const ADD_USER_TO_GROUP_SUCCESS = 'ADD_USER_TO_GROUP_SUCCESS'
export const ADD_USER_TO_GROUP_FAIL = 'ADD_USER_TO_GROUP_FAIL'


export const DELETE_USER_FROM_GROUP = 'DELETE_USER_FROM_GROUP'
export const DELETE_USER_FROM_GROUP_SUCCESS = 'DELETE_USER_FROM_GROUP_SUCCESS'
export const DELETE_USER_FROM_GROUP_FAIL = 'DELETE_USER_FROM_GROUP_FAIL'


//fields
export const CREATE_FIELD = 'CREATE_FIELD'
export const CREATE_FIELD_SUCCESS = 'CREATE_FIELD_SUCCESS'
export const CREATE_FIELD_FAIL = 'CREATE_FIELD_FAIL'

export const DELETE_FIELD = 'DELETE_FIELD'
export const DELETE_FIELD_SUCCESS = 'DELETE_FIELD_SUCCESS'
export const DELETE_FIELD_FAIL = 'DELETE_FIELD_FAIL'
